@extends('layouts.guest')

@section('content')
<div class="card p-4 shadow">
    <h2 class="mb-3">Enable Two-Factor Authentication</h2>

    @if(!$qrCodeUrl)
    {{-- Show button when no QR yet --}}
    <form method="POST" action="{{ route('twofa.generate') }}">
        @csrf
        <button type="submit" class="btn btn-primary w-100">
            Generate QR Code
        </button>
    </form>
    @else
    {{-- Show QR + form if generated --}}
    <ol class="mb-4">
        <li>Download <strong>Google Authenticator</strong> from Play Store or App Store.</li>
        <li>Scan the QR code below using the app.</li>
        <li>Enter the 6-digit code generated by the app.</li>
    </ol>

    <div class="text-center mb-3">
        {!! QrCode::size(200)->generate($qrCodeUrl) !!}
    </div>


    <p class="text-muted text-center">
        Or enter this secret manually: <strong>{{ $secret }}</strong>
    </p>

    <form method="POST" action="{{ route('twofa.verify') }}" class="mt-4">
        @csrf
        <div class="mb-3">
            <label for="otp" class="form-label">Enter 6-digit Code</label>
            <input type="text" name="otp" id="otp" class="form-control" placeholder="123456" required>
        </div>
        <button type="submit" class="btn btn-success w-100">Verify & Enable 2FA</button>
    </form>
    @endif

    <div class="mt-3">
        <a href="{{ route('dashboard') }}" class="btn btn-secondary w-100">Skip for Now</a>
    </div>
</div>
@endsection