<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountriesTableSeeder extends Seeder
{
    public function run(): void
    {
        $countries = [
            [
                'country_name' => 'United States',
                'country_code' => 'US',
                'country_tel_code' => '+1',
                'country_time_zone' => 'America/New_York',
                'country_currency' => 'US Dollar',
                'country_currency_symbol' => '$',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_name' => 'Canada',
                'country_code' => 'CA',
                'country_tel_code' => '+1',
                'country_time_zone' => 'America/Toronto',
                'country_currency' => 'Canadian Dollar',
                'country_currency_symbol' => 'C$',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_name' => 'United Kingdom',
                'country_code' => 'GB',
                'country_tel_code' => '+44',
                'country_time_zone' => 'Europe/London',
                'country_currency' => 'British Pound',
                'country_currency_symbol' => '£',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_name' => 'Germany',
                'country_code' => 'DE',
                'country_tel_code' => '+49',
                'country_time_zone' => 'Europe/Berlin',
                'country_currency' => 'Euro',
                'country_currency_symbol' => '€',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_name' => 'France',
                'country_code' => 'FR',
                'country_tel_code' => '+33',
                'country_time_zone' => 'Europe/Paris',
                'country_currency' => 'Euro',
                'country_currency_symbol' => '€',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_name' => 'Australia',
                'country_code' => 'AU',
                'country_tel_code' => '+61',
                'country_time_zone' => 'Australia/Sydney',
                'country_currency' => 'Australian Dollar',
                'country_currency_symbol' => 'A$',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_name' => 'Japan',
                'country_code' => 'JP',
                'country_tel_code' => '+81',
                'country_time_zone' => 'Asia/Tokyo',
                'country_currency' => 'Japanese Yen',
                'country_currency_symbol' => '¥',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_name' => 'China',
                'country_code' => 'CN',
                'country_tel_code' => '+86',
                'country_time_zone' => 'Asia/Shanghai',
                'country_currency' => 'Chinese Yuan',
                'country_currency_symbol' => '¥',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_name' => 'India',
                'country_code' => 'IN',
                'country_tel_code' => '+91',
                'country_time_zone' => 'Asia/Kolkata',
                'country_currency' => 'Indian Rupee',
                'country_currency_symbol' => '₹',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_name' => 'Brazil',
                'country_code' => 'BR',
                'country_tel_code' => '+55',
                'country_time_zone' => 'America/Sao_Paulo',
                'country_currency' => 'Brazilian Real',
                'country_currency_symbol' => 'R$',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_name' => 'Russia',
                'country_code' => 'RU',
                'country_tel_code' => '+7',
                'country_time_zone' => 'Europe/Moscow',
                'country_currency' => 'Russian Ruble',
                'country_currency_symbol' => '₽',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_name' => 'Mexico',
                'country_code' => 'MX',
                'country_tel_code' => '+52',
                'country_time_zone' => 'America/Mexico_City',
                'country_currency' => 'Mexican Peso',
                'country_currency_symbol' => '$',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_name' => 'Italy',
                'country_code' => 'IT',
                'country_tel_code' => '+39',
                'country_time_zone' => 'Europe/Rome',
                'country_currency' => 'Euro',
                'country_currency_symbol' => '€',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_name' => 'Spain',
                'country_code' => 'ES',
                'country_tel_code' => '+34',
                'country_time_zone' => 'Europe/Madrid',
                'country_currency' => 'Euro',
                'country_currency_symbol' => '€',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_name' => 'South Korea',
                'country_code' => 'KR',
                'country_tel_code' => '+82',
                'country_time_zone' => 'Asia/Seoul',
                'country_currency' => 'South Korean Won',
                'country_currency_symbol' => '₩',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_name' => 'Turkey',
                'country_code' => 'TR',
                'country_tel_code' => '+90',
                'country_time_zone' => 'Europe/Istanbul',
                'country_currency' => 'Turkish Lira',
                'country_currency_symbol' => '₺',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_name' => 'Netherlands',
                'country_code' => 'NL',
                'country_tel_code' => '+31',
                'country_time_zone' => 'Europe/Amsterdam',
                'country_currency' => 'Euro',
                'country_currency_symbol' => '€',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_name' => 'Switzerland',
                'country_code' => 'CH',
                'country_tel_code' => '+41',
                'country_time_zone' => 'Europe/Zurich',
                'country_currency' => 'Swiss Franc',
                'country_currency_symbol' => 'CHF',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_name' => 'Sweden',
                'country_code' => 'SE',
                'country_tel_code' => '+46',
                'country_time_zone' => 'Europe/Stockholm',
                'country_currency' => 'Swedish Krona',
                'country_currency_symbol' => 'kr',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_name' => 'Norway',
                'country_code' => 'NO',
                'country_tel_code' => '+47',
                'country_time_zone' => 'Europe/Oslo',
                'country_currency' => 'Norwegian Krone',
                'country_currency_symbol' => 'kr',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_name' => 'Denmark',
                'country_code' => 'DK',
                'country_tel_code' => '+45',
                'country_time_zone' => 'Europe/Copenhagen',
                'country_currency' => 'Danish Krone',
                'country_currency_symbol' => 'kr',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_name' => 'Finland',
                'country_code' => 'FI',
                'country_tel_code' => '+358',
                'country_time_zone' => 'Europe/Helsinki',
                'country_currency' => 'Euro',
                'country_currency_symbol' => '€',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_name' => 'Poland',
                'country_code' => 'PL',
                'country_tel_code' => '+48',
                'country_time_zone' => 'Europe/Warsaw',
                'country_currency' => 'Polish Złoty',
                'country_currency_symbol' => 'zł',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_name' => 'Argentina',
                'country_code' => 'AR',
                'country_tel_code' => '+54',
                'country_time_zone' => 'America/Argentina/Buenos_Aires',
                'country_currency' => 'Argentine Peso',
                'country_currency_symbol' => '$',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_name' => 'South Africa',
                'country_code' => 'ZA',
                'country_tel_code' => '+27',
                'country_time_zone' => 'Africa/Johannesburg',
                'country_currency' => 'South African Rand',
                'country_currency_symbol' => 'R',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_name' => 'Egypt',
                'country_code' => 'EG',
                'country_tel_code' => '+20',
                'country_time_zone' => 'Africa/Cairo',
                'country_currency' => 'Egyptian Pound',
                'country_currency_symbol' => 'E£',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_name' => 'Nigeria',
                'country_code' => 'NG',
                'country_tel_code' => '+234',
                'country_time_zone' => 'Africa/Lagos',
                'country_currency' => 'Nigerian Naira',
                'country_currency_symbol' => '₦',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_name' => 'Kenya',
                'country_code' => 'KE',
                'country_tel_code' => '+254',
                'country_time_zone' => 'Africa/Nairobi',
                'country_currency' => 'Kenyan Shilling',
                'country_currency_symbol' => 'KSh',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_name' => 'Saudi Arabia',
                'country_code' => 'SA',
                'country_tel_code' => '+966',
                'country_time_zone' => 'Asia/Riyadh',
                'country_currency' => 'Saudi Riyal',
                'country_currency_symbol' => '﷼',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_name' => 'United Arab Emirates',
                'country_code' => 'AE',
                'country_tel_code' => '+971',
                'country_time_zone' => 'Asia/Dubai',
                'country_currency' => 'UAE Dirham',
                'country_currency_symbol' => 'د.إ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_name' => 'Israel',
                'country_code' => 'IL',
                'country_tel_code' => '+972',
                'country_time_zone' => 'Asia/Jerusalem',
                'country_currency' => 'Israeli Shekel',
                'country_currency_symbol' => '₪',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_name' => 'Thailand',
                'country_code' => 'TH',
                'country_tel_code' => '+66',
                'country_time_zone' => 'Asia/Bangkok',
                'country_currency' => 'Thai Baht',
                'country_currency_symbol' => '฿',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_name' => 'Malaysia',
                'country_code' => 'MY',
                'country_tel_code' => '+60',
                'country_time_zone' => 'Asia/Kuala_Lumpur',
                'country_currency' => 'Malaysian Ringgit',
                'country_currency_symbol' => 'RM',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_name' => 'Singapore',
                'country_code' => 'SG',
                'country_tel_code' => '+65',
                'country_time_zone' => 'Asia/Singapore',
                'country_currency' => 'Singapore Dollar',
                'country_currency_symbol' => 'S$',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_name' => 'Indonesia',
                'country_code' => 'ID',
                'country_tel_code' => '+62',
                'country_time_zone' => 'Asia/Jakarta',
                'country_currency' => 'Indonesian Rupiah',
                'country_currency_symbol' => 'Rp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_name' => 'Vietnam',
                'country_code' => 'VN',
                'country_tel_code' => '+84',
                'country_time_zone' => 'Asia/Ho_Chi_Minh',
                'country_currency' => 'Vietnamese Dong',
                'country_currency_symbol' => '₫',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_name' => 'Philippines',
                'country_code' => 'PH',
                'country_tel_code' => '+63',
                'country_time_zone' => 'Asia/Manila',
                'country_currency' => 'Philippine Peso',
                'country_currency_symbol' => '₱',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_name' => 'Pakistan',
                'country_code' => 'PK',
                'country_tel_code' => '+92',
                'country_time_zone' => 'Asia/Karachi',
                'country_currency' => 'Pakistani Rupee',
                'country_currency_symbol' => '₨',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_name' => 'Bangladesh',
                'country_code' => 'BD',
                'country_tel_code' => '+880',
                'country_time_zone' => 'Asia/Dhaka',
                'country_currency' => 'Bangladeshi Taka',
                'country_currency_symbol' => '৳',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_name' => 'Iran',
                'country_code' => 'IR',
                'country_tel_code' => '+98',
                'country_time_zone' => 'Asia/Tehran',
                'country_currency' => 'Iranian Rial',
                'country_currency_symbol' => '﷼',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_name' => 'Iraq',
                'country_code' => 'IQ',
                'country_tel_code' => '+964',
                'country_time_zone' => 'Asia/Baghdad',
                'country_currency' => 'Iraqi Dinar',
                'country_currency_symbol' => 'ع.د',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_name' => 'Ukraine',
                'country_code' => 'UA',
                'country_tel_code' => '+380',
                'country_time_zone' => 'Europe/Kiev',
                'country_currency' => 'Ukrainian Hryvnia',
                'country_currency_symbol' => '₴',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_name' => 'Portugal',
                'country_code' => 'PT',
                'country_tel_code' => '+351',
                'country_time_zone' => 'Europe/Lisbon',
                'country_currency' => 'Euro',
                'country_currency_symbol' => '€',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_name' => 'Greece',
                'country_code' => 'GR',
                'country_tel_code' => '+30',
                'country_time_zone' => 'Europe/Athens',
                'country_currency' => 'Euro',
                'country_currency_symbol' => '€',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_name' => 'Ireland',
                'country_code' => 'IE',
                'country_tel_code' => '+353',
                'country_time_zone' => 'Europe/Dublin',
                'country_currency' => 'Euro',
                'country_currency_symbol' => '€',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_name' => 'Austria',
                'country_code' => 'AT',
                'country_tel_code' => '+43',
                'country_time_zone' => 'Europe/Vienna',
                'country_currency' => 'Euro',
                'country_currency_symbol' => '€',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_name' => 'Belgium',
                'country_code' => 'BE',
                'country_tel_code' => '+32',
                'country_time_zone' => 'Europe/Brussels',
                'country_currency' => 'Euro',
                'country_currency_symbol' => '€',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_name' => 'Czech Republic',
                'country_code' => 'CZ',
                'country_tel_code' => '+420',
                'country_time_zone' => 'Europe/Prague',
                'country_currency' => 'Czech Koruna',
                'country_currency_symbol' => 'Kč',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_name' => 'Hungary',
                'country_code' => 'HU',
                'country_tel_code' => '+36',
                'country_time_zone' => 'Europe/Budapest',
                'country_currency' => 'Hungarian Forint',
                'country_currency_symbol' => 'Ft',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_name' => 'Romania',
                'country_code' => 'RO',
                'country_tel_code' => '+40',
                'country_time_zone' => 'Europe/Bucharest',
                'country_currency' => 'Romanian Leu',
                'country_currency_symbol' => 'lei',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_name' => 'Chile',
                'country_code' => 'CL',
                'country_tel_code' => '+56',
                'country_time_zone' => 'America/Santiago',
                'country_currency' => 'Chilean Peso',
                'country_currency_symbol' => '$',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_name' => 'Colombia',
                'country_code' => 'CO',
                'country_tel_code' => '+57',
                'country_time_zone' => 'America/Bogota',
                'country_currency' => 'Colombian Peso',
                'country_currency_symbol' => '$',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_name' => 'Peru',
                'country_code' => 'PE',
                'country_tel_code' => '+51',
                'country_time_zone' => 'America/Lima',
                'country_currency' => 'Peruvian Sol',
                'country_currency_symbol' => 'S/',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_name' => 'New Zealand',
                'country_code' => 'NZ',
                'country_tel_code' => '+64',
                'country_time_zone' => 'Pacific/Auckland',
                'country_currency' => 'New Zealand Dollar',
                'country_currency_symbol' => 'NZ$',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('countries')->insert($countries);
    }
}
